4.1

In [3]:
import numpy as np

In [12]:
data = np.random.randn(3, 3)

In [13]:
data

array([[-1.96002621e+00,  3.89990477e-01,  1.53455344e-03],
       [ 2.64694658e-01,  2.49280320e-02,  3.68054367e-02],
       [ 6.14200873e-02,  3.91813939e-02,  1.93355737e+00]])

In [10]:
data * 10

array([[-2.27123788,  3.56106395, -0.78200096],
       [-9.62386201, -4.05337001,  4.51540277],
       [ 3.1324073 ,  3.60017541, -2.81488587]])

In [11]:
data + data

array([[-0.45424758,  0.71221279, -0.15640019],
       [-1.9247724 , -0.810674  ,  0.90308055],
       [ 0.62648146,  0.72003508, -0.56297717]])

In [13]:
data.shape

(3, 3)

In [14]:
data.dtype

dtype('float64')

In [15]:
data1=[6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)


In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
np.empty((2,3,2))

array([[[1.38795077e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 8.37526556e+169]],

       [[1.39336299e+165, 1.46420503e-075],
        [8.01206209e+165, 2.38393703e+180],
        [1.86392828e+160, 4.95419897e-062]]])

In [31]:
np.arange(100,130)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [32]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [34]:
arr2 = np.array([1, 2, 3], dtype=np.int32)


In [35]:
arr1.dtype

dtype('float64')

In [36]:
arr2.dtype

dtype('int32')

In [37]:
arr = np.array([1, 2, 3, 4, 5])

In [38]:
arr.dtype

dtype('int32')

In [39]:
float_arr = arr.astype(np.float64)

In [40]:
float_arr.dtype

dtype('float64')

In [41]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])


In [42]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [43]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [44]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)


In [45]:
numeric_strings.astype(float)


array([ 1.25, -9.6 , 42.  ])

In [46]:
int_arr=np.arange(10)

In [47]:
int_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)


In [50]:
int_arr.astype(calibers.dtype)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
empty_uint32 = np.empty(8, dtype='u4')


In [53]:
empty_uint32


array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [54]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [55]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [57]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [59]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [60]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])


In [61]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [62]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[6]

6

In [6]:
arr[3]

3

In [7]:
arr[5:8]

array([5, 6, 7])

In [8]:
arr[5:8] = 12

In [9]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [10]:
arr_slice = arr[5:8]

In [11]:
arr_slice

array([12, 12, 12])

In [12]:
arr_slice[1] = 12345

In [13]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [14]:
arr_slice[:] = 64

In [15]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [17]:
arr2d[2]

array([7, 8, 9])

In [18]:
arr2d[0][2]

3

In [19]:
arr2d[0, 2]

3

In [20]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [21]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [24]:
old_values = arr3d[0].copy()

In [25]:
arr3d[0] = 42

In [27]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr3d[0] = old_values

In [29]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[1, 0]

array([7, 8, 9])

In [31]:
x = arr3d[1]

In [32]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [5]:
arr2d[1, :2]

array([4, 5])

In [6]:
arr2d[:2, 2]

array([3, 6])

In [7]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [8]:
np.random.randn(7, 4)

array([[-0.52502967,  0.03494338,  0.1424495 ,  0.41286713],
       [-1.3349944 , -1.41001525,  0.22616575, -0.44022145],
       [ 0.17052485,  0.27898047, -1.52276668, -0.1743067 ],
       [ 1.04516368,  0.96059233, -1.72563331, -0.47261939],
       [ 1.14817421, -1.52934209, -0.67030979, -0.58847085],
       [ 1.84971151, -0.77475056, -1.41721631, -0.41124546],
       [ 1.66727818,  0.58908987, -0.2746349 , -0.20247207]])

In [9]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [14]:
data

array([[-1.96002621e+00,  3.89990477e-01,  1.53455344e-03],
       [ 2.64694658e-01,  2.49280320e-02,  3.68054367e-02],
       [ 6.14200873e-02,  3.91813939e-02,  1.93355737e+00]])

In [15]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [16]:
data[names == 'Bob']

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 7

In [17]:
data[names == 'Bob', 2:]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 7

In [18]:
mask = (names == 'Bob') | (names == 'Will')

In [19]:
mask

array([ True, False,  True,  True,  True, False, False])

In [20]:
data[mask]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 7

In [21]:
data[data < 0] = 0

In [22]:
data

array([[0.00000000e+00, 3.89990477e-01, 1.53455344e-03],
       [2.64694658e-01, 2.49280320e-02, 3.68054367e-02],
       [6.14200873e-02, 3.91813939e-02, 1.93355737e+00]])

In [25]:
arr = np.empty((8, 4))
for i in range(8):
     arr[i] = i

In [26]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [27]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [28]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [29]:
arr = np.arange(32).reshape((8, 4))

In [30]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [31]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [32]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [33]:
arr = np.arange(15).reshape((3, 5))

In [34]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [36]:
arr = np.random.randn(6, 3)

In [37]:
arr

array([[-1.21521786, -1.12251242, -2.583423  ],
       [-1.85944693,  0.83817672,  1.81598136],
       [ 0.62450026, -1.2389577 , -0.30526459],
       [-1.74903594,  0.35428728, -0.20089485],
       [-0.49289661,  1.27026518,  1.14170459],
       [-1.25132167,  0.91281257, -1.22906918]])

In [38]:
np.dot(arr.T, arr)

array([[10.19217763, -3.35617013,  0.89865387],
       [-3.35617013,  6.06991041,  5.05743091],
       [ 0.89865387,  5.05743091, 12.9195083 ]])

In [39]:
arr = np.arange(16).reshape((2, 2, 4))

In [40]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [41]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [42]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [43]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [44]:
arr = np.arange(10)

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [47]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [48]:
x = np.random.randn(8)

In [49]:
x

array([ 1.25413037, -1.36842852, -1.32817909,  1.2578144 ,  0.38073652,
        0.55202389,  1.09268708, -2.47234741])

In [50]:
y = np.random.randn(8)

In [51]:
y

array([ 1.48288078, -0.07649319, -1.56113479,  1.93170163,  0.32177415,
       -0.40314556, -0.60640358, -0.15913619])

In [52]:
np.maximum(x, y)

array([ 1.48288078, -0.07649319, -1.32817909,  1.93170163,  0.38073652,
        0.55202389,  1.09268708, -0.15913619])

In [53]:
arr = np.random.randn(7) * 5

In [54]:
arr

array([ -3.94239888,   5.14766748,   2.36792905, -10.33903731,
        -2.48439978,   3.62976188,   0.1079674 ])

In [55]:
remainder, whole_part = np.modf(arr)

In [56]:
remainder

array([-0.94239888,  0.14766748,  0.36792905, -0.33903731, -0.48439978,
        0.62976188,  0.1079674 ])

In [57]:
whole_part

array([ -3.,   5.,   2., -10.,  -2.,   3.,   0.])

In [58]:
arr

array([ -3.94239888,   5.14766748,   2.36792905, -10.33903731,
        -2.48439978,   3.62976188,   0.1079674 ])

In [59]:
np.sqrt(arr)

<ipython-input-59-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan, 2.26884717, 1.53880767,        nan,        nan,
       1.9051934 , 0.32858393])

In [60]:
np.sqrt(arr, arr)

<ipython-input-60-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan, 2.26884717, 1.53880767,        nan,        nan,
       1.9051934 , 0.32858393])

In [61]:
arr

array([       nan, 2.26884717, 1.53880767,        nan,        nan,
       1.9051934 , 0.32858393])

4.5

In [62]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [63]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [64]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [65]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [66]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [68]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [69]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [70]:
x @ np.ones(3)

array([ 6., 15.])

In [71]:
from numpy.linalg import inv, qr

In [72]:
X = np.random.randn(5, 5)

In [73]:
mat = X.T.dot(X)

In [74]:
inv(mat)

array([[ 0.69210071,  0.44540938,  0.19628658,  0.12492847, -0.15987681],
       [ 0.44540938,  1.51405642,  1.08986915, -0.0015366 ,  1.00725121],
       [ 0.19628658,  1.08986915,  1.24308877, -0.01313424,  1.0632426 ],
       [ 0.12492847, -0.0015366 , -0.01313424,  0.19851955, -0.04213935],
       [-0.15987681,  1.00725121,  1.0632426 , -0.04213935,  1.31383682]])

In [75]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.78371488e-16, -2.34606869e-16,
        -7.45905736e-17, -1.02087548e-16],
       [-1.69651233e-17,  1.00000000e+00,  1.73841237e-16,
         1.56940072e-16, -4.11080876e-16],
       [ 5.60941916e-16,  7.55450759e-16,  1.00000000e+00,
         5.12793206e-17,  1.86326764e-16],
       [ 2.10360243e-16,  1.01150718e-17,  1.26078633e-16,
         1.00000000e+00, -5.46385409e-16],
       [-7.56706789e-16, -2.47985831e-16,  8.93266623e-16,
        -1.61134995e-16,  1.00000000e+00]])

In [76]:
q, r = qr(mat)

In [77]:
r

array([[-10.81514122,   7.01059768,   5.65484801,   6.29247009,
        -11.48961492],
       [  0.        ,  -2.23299921,   3.19517118,   0.70063294,
         -0.83027344],
       [  0.        ,   0.        ,  -2.42596639,   2.47079862,
          2.41854993],
       [  0.        ,   0.        ,   0.        ,  -4.28578081,
         -0.10907045],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.50646428]])